### ISSUE TITLE
Why no access_token on put requests?

### ISSUE THREAD

**Issue by sheerun** [taskcluster/livelog#8]
Hey! 

I was wondering why isn't there authentication for PUT requests? Isn't it insecure?

**Comment by jonasfj** [comment]
The way we use it in docker-worker we create a docker container with the livelogger, then we pipe the log to that container. The trick is that docker creates a virtual network, and we only expose the port hosting the `GET` interface from the container, so the outside world can't possibly access the `PUT` interface, because the port isn't exposed.

>  Isn't it insecure?

It might very well be in generic-worker, I must admit I haven't kept up with the code recently.
