### ISSUE TITLE
Http authentication instead param in query

### ISSUE THREAD

**Issue by sheerun** [taskcluster/livelog#9]
Hey,

I've noticed you encourage to put secret in GET url. Wouldn't it be better to use http auth header?

**Comment by jonasfj** [comment]
Auth headers are **always** better! :)
I totally agree... This is sort of a special use-case where we glue together a few components.

The way we use the livelogger is that we create a secret url, by putting a random secret in the URL.

We then create a _redirect artifact_ on `queue.taskcluster.net`, such that a request for the artifact is redirected to the secret url (which serves the livelog).

On `queue.taskcluster.net` (see docs.taskcluster.net/queue/api-docs/  particularly: getArtifact) we require a special scope "queue:get-artifact:<name>" to get an artifact called "<name>".
**Unless** the artifact name starts with `public/`, then we don't require any authentication. At the moment the live log artifact is always called `public/logs/live.log`, but if we ever need get private logs for tests of security patches etc. we could put those logs in `team/sec-team/live.log` and ensure that only members of the security team have the scope "queue:get-artifact:team/sec-team/*".

Basically, all the secret in the URL does is ensure that the requester was redirected to the livelog from `queue.taskcluster.net`, which handles the authentication.
Since the task is fairly short lived, the secret won't be relevant for long, so this seems like an acceptable security-level. Similar to the security of a signed URL for an S3 object.
(as everything is HTTPS the secret url isn't easily leaked anyways)

------
If you want to contribute and play around with some of this you are welcome to join us on IRC (#taskcluster on irc.mozilla.org), we can set you up with some credentials. We generally hang out on IRC all the time (I'm also available by email `jopsen@gmail.com`).
Next week we'll all be in the US for a work week, but generally petemoore (generic worker) and jhford are in Germany. Me and gregarndt (docker-worker) are in the US.
